### ISSUE TITLE
Следим за операторами.

### ISSUE THREAD

**Issue by radetsky** [radetsky/Pearl-PBX#24]
С помощью приложения QueueLog или веб-сайта нужно предоставить возможность оператору расширить свой статус. Не только "Ушел, пришел", но и "пошел попить кофе", "завтрак","перекур" и т.д. 
Это должно централизованно писаться и отслеживаться администратором. 

voip*CLI> core show application QueueLog

  -= Info about application 'QueueLog' =-

[Synopsis]
Writes to the queue_log file.

[Description]
Allows you to write your own events into the queue log.
Example: QueueLog(101,${UNIQUEID},${AGENT},WENTONBREAK,600)

[Syntax]
QueueLog(queuename,uniqueid,agent,event[,additionalinfo])

[Arguments]
Not available

[See Also]
Queue(), QueueLog(), AddQueueMember(), RemoveQueueMember(), PauseQueueMember(),
UnpauseQueueMember(), QUEUE_VARIABLES, QUEUE_MEMBER, QUEUE_MEMBER_COUNT,
QUEUE_EXISTS, QUEUE_WAITING_COUNT, QUEUE_MEMBER_LIST, QUEUE_MEMBER_PENALT

**Comment by Telegramsrv** [comment]
Где посмотреть реализацию диаплана с установкой различных статусов перерывов? 
тут нашел небольшой пример, где устанавливает оператор паузу и снимает https://voxlink.ru/kb/asterisk-configuration/queue-pause-unpause/

**Comment by radetsky** [comment]
В этом проекте это не реализовано. Текущим клиентам это не надо, а новых я стараюсь не брать.
